### ISSUE TITLE
TypeError: docstore.put is not a function

### ISSUE THREAD

**Issue by amitmoralwar** [orbitdb/orbit-db-docstore#23]
I am trying to run following code but I am getting "TypeError: docstore.put is not a function" . Error
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfs = new IPFS()
const orbitdb = new OrbitDB(ipfs)
const docstore = orbitdb.docstore('todo2')

docstore.put({ _id: 'hello world', doc: 'all the things' })
  .then(() => docstore.put({ _id: 'sup world', doc: 'other things' }))
  .then(() => docstore.get('hello'))
  .then((value) => console.log(value))

**Comment by aphelionz** [comment]
This line:

const docstore = orbitdb.docstore('todo2')

Will require an await

**Comment by siddhudhangar** [comment]
i am also facing same issue. can you please tell me how to write the await into above line of code ? . it would be helpful to me if you solve the above issue.

**Comment by aphelionz** [comment]
Sorry, yes.

Please try using await to replace the promises like so:

```javascript
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfs = new IPFS()
const orbitdb = new OrbitDB(ipfs)
const docstore = await orbitdb.docstore('todo2')

await docstore.put({ _id: 'hello world', doc: 'all the things' })
await docstore.put({ _id: 'sup world', doc: 'other things' }))
const value = docstore.get('hello'))
console.log(value)
```

**Comment by siddhudhangar** [comment]
I ran above program then i got following error.
const docstore = await orbitdb.docstore('todo2')
                 ^^^^^
SyntaxError: await is only valid in async function
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by siddhudhangar** [comment]
I have written await in async function.

const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfs = new IPFS()
const orbitdb = new OrbitDB(ipfs)
const docstore = async function(){

//await orbitdb.docstore('todo2')
await orbitdb.docstore('todo2').put({ _id: 'hello world', doc: 'all the things' })
await orbitdb.docstore('todo2').put({ _id: 'sup world', doc: 'other things' })
const value = orbitdb.docstore('todo2').get('hello')
console.log(value)

}
docstore();

i ran above code. now i got another error.
/home/glab/my_workspace/orbit-db-docstore/node_modules/ipfs-block-service/src/index.js:64
      this._repo.blocks.put(block, callback)
                        ^

TypeError: Cannot read property 'put' of undefined
    at BlockService.put (/home/glab/my_workspace/orbit-db-docstore/node_modules/ipfs-block-service/src/index.js:64:25)
    at waterfall (/home/glab/my_workspace/orbit-db-docstore/node_modules/ipld/src/index.js:392:28)
    at nextTask (/home/glab/my_workspace/orbit-db-docstore/node_modules/async/waterfall.js:16:14)
    at next (/home/glab/my_workspace/orbit-db-docstore/node_modules/async/waterfall.js:23:9)
    at /home/glab/my_workspace/orbit-db-docstore/node_modules/async/internal/onlyOnce.js:12:16
    at Object.serialize (/home/glab/my_workspace/orbit-db-docstore/node_modules/ipld-dag-pb/src/util.js:76:3)
    at waterfall (/home/glab/my_workspace/orbit-db-docstore/node_modules/ipld/src/index.js:391:35)
    at nextTask (/home/glab/my_workspace/orbit-db-docstore/node_modules/async/waterfall.js:16:14)
    at next (/home/glab/my_workspace/orbit-db-docstore/node_modules/async/waterfall.js:23:9)
    at /home/glab/my_workspace/orbit-db-docstore/node_modules/async/internal/onlyOnce.js:12:16

**Comment by RichardLitt** [comment]
@amitmoralwar 	and @siddhudhangar did you get your questions answered?
